@extends('layouts.frontend')

@section('content')


<!-- Class Timetable Start -->
<div class="container-fluid p-5">
    <div class="mb-5 text-center">
        <h5 class="text-primary text-uppercase"></h5>
        <h1 class="display-3 text-uppercase mb-0">Working Routine</h1>
    </div>
    <div class="tab-class text-center">
        <div class="tab-content">
            <div id="tab-1" class="tab-pane fade show p-0 active">
                <div class="row g-5">
                @foreach($categories as $category)
                    <div class="col-md-3 col-md-4 col-sm-6">
                        <a href="{{ url('workouts/'.$category->description) }}">
                        <div class="rowlo bg-dark rounded text-center py-5 px-3">
                            <h6 class="text-uppercase text-light mb-3">Day</h6>
                            <h1 class="text-uppercase text-primary">{{ $category->description }}</h1>
                            <p class="text-uppercase text-secondary mb-0" style="font-size: 11px;">Flex Condam Fit</p>
                        </div>
                        </a>
                    </div>
                @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Class Timetable Start -->

<!-- Programe Start -->
<div class="container-fluid programe position-relative px-5 mt-5" style="margin-bottom: 135px;">
    <div class="row g-5 gb-5">
        <div class="col-lg-4 col-md-6">
            <div class="bg-light rounded text-center p-5">
                <i class="flaticon-six-pack display-1 text-primary"></i>
                <h3 class="text-uppercase my-4">Body Building</h3>
                <p>Bodybuilding is the use of progressive resistance exercise to control and develop one's muscles by muscle hypertrophy for aesthetic purposes. It is distinct from similar activities such as powerlifting because it focuses more on physical appearance instead of strength.</p>
                <!-- <a class="text-uppercase" onclick="myFunction()" id="myBtn">Read More <i class="bi bi-arrow-right"></i></a> -->
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="bg-light rounded text-center p-5">
                <i class="flaticon-barbell display-1 text-primary"></i>
                <h3 class="text-uppercase my-4">Weight Lifting</h3>
                <p>Weight training is a common type of strength training for developing the strength, size of skeletal muscles and maintenance of strength. It uses the force of gravity in the form of weighted bars, dumbbells or weight stacks in order to oppose the force generated by muscle through concentric or eccentric contraction.</p>
                <!-- <a class="text-uppercase" href="">Read More <i class="bi bi-arrow-right"></i></a> -->
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="bg-light rounded text-center p-5">
                <i class="flaticon-bodybuilding display-1 text-primary"></i>
                <h3 class="text-uppercase my-4">Muscle Building</h3>
                <p>This process of increasing your muscle mass is known as muscle hypertrophy, and it's a primary goal of resistance training. The muscle building process is driven by several factors, including hormones like testosterone and growth hormone, as well as the availability of amino acids and other nutrients.</p>
                <!-- <a class="text-uppercase" href="">Read More <i class="bi bi-arrow-right"></i></a> -->
            </div>
        </div>
        <div class="col-lg-12 col-md-6 text-center">
            <h1 class="text-uppercase text-light mb-4">30% Discount For This Summer</h1>
            <a href="" class="btn btn-primary py-3 px-5">Become A Member</a>
        </div>
    </div>
</div>
<!-- Programe Start -->

@endsection